### PR TITLE
Support Uniswap v2 and a bunch of other major changes

### LINKED ISSUE #10: Support Uniswap v2
I'm working on Uniswap v2 support (and a lot of other things) in my fork: https://github.com/ErikBjare/uniswap-python

Specifically this PR: https://github.com/ErikBjare/uniswap-python/pull/1

I'd be interested in getting it into upstream eventually, if that's of interest to you @shanefontaine

### PR DESCRIPTION
**Pull request by ErikBjare**
I'm not sure how willing you are to accept huge diffs like this, but I thought I'd post it here for your review.

 - Added support for Uniswap v2
 - Handle arbitrary tokens (by address) using the factory contract
 - Switched from setup.py to pyproject.toml/poetry
 - Switched from Travis to GitHub Actions
   - For CI to work in your repo, you need to set the secret `MAINNET_PROVIDER`. I use Infura.
 - Running tests on a local fork of mainnet using ganache-cli (started as a fixture)
 - Fixed tests for make_trade and make_trade_output
 - Added type annotations to the entire codebase and check them with mypy in CI
 - Formatted entire codebase with black
 - Moved stuff around such that the basic import becomes `from uniswap import Uniswap` (instead of `from uniswap.uniswap import UniswapWrapper`)
 - Fixed misc bugs

**NOTE:** I've probably broken a lot of things, so might make sense to bump the release number to a new major version.

There's some stale code that isn't covered by tests, I could look into tidying that up if you consider it a blocker for merging.

If you don't want to merge this right now (understandable) and just want the V2 changes, ~~you'll have to wait a bit~~, but I thought it wouldn't hurt to let you know of the progress so far :slightly_smiling_face: 

Fixes #10

### CODE REVIEW

**Comment by ErikBjare** [comment]
Well, that was easy. 

Uniswap v2 support complete. It always uses ETH as a middle pair for token-token swaps, but I assume that's a reasonable assumption since ETH pairs seem to dominate available liquidity anyway (https://uniswap.info).

**Comment by ErikBjare** [comment]
Since CI doesn't seem to run in your repo (it makes sense given that you don't have secrets configured) you can see a CI run here: https://github.com/ErikBjare/uniswap-python/runs/906682611

**Comment by ErikBjare** [comment]
@shanefontaine I think the last commit fixed the remaining bugs. Any change of this getting merged?

**Comment by shanefontaine** [comment]
@ErikBjare Thank you for this work. I will review this week and let you know if anything comes up! Some, if not all, of this will definitely be merged.

**Comment by shanefontaine** [comment]
@ErikBjare great work! I'd be happy to add your username more prominently as an author and/or contributor. Please let me know if you have any ideas to get you more recognition and I'd be happy to do so!

**Pull request merged**
